compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  hacksis:
    npmAlwaysAuth: true
    npmAuthIdent: aGFja3NpczozZHY4OFhQQWZnVmtxMDAxSjZPdnYwenZRclpnS2I2MkV1QWw0cmVVbVdUVzhBcXc2Y0FySlFRSjk5QkJBQ0FBQUFBTE9FdXJBQUFTQVpETzRCTGY=
    npmPublishRegistry: "https://pkgs.dev.azure.com/Hacksis/_packaging/Hacksis/npm/registry"
    npmRegistryServer: "https://pkgs.dev.azure.com/Hacksis/_packaging/Hacksis/npm/registry"